<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $escaper \Magento\Framework\Escaper
 * @var $viewModel \Crimson\CartTopMessages\ViewModel\ConfigurableMessage
 * ZIP-1653
 */

$viewModel = $block->getViewModel();
if (!$viewModel) return;

?>

<div class="configurable-messages" aria-atomic="true" role="alert">
    <?php foreach ($viewModel->getMessages() as $i => $message): ?>
        <div class="message-success success message num-<?= $i ?>">
            <div><?= $escaper->escapeHtml($message) ?></div>
        </div>
    <?php endforeach; ?>
</div>
