<?php
// @codingStandardsIgnoreFile
$ga4ServerSideHelper = $this->helper('WeltPixel\GA4\Helper\ServerSideTracking');
$helper = $this->helper('WeltPixel\GA4\Helper\Data');
?>
<?php if($this->isEnabled()) : ?>
    <?php $category = $this->getCurrentCategory(); ?>
    <?php $gtmCategoryLabel = $helper->getGtmCategory($category); ?>
<?php if (!($ga4ServerSideHelper->isServerSideTrakingEnabled() && $ga4ServerSideHelper->shouldEventBeTracked(\WeltPixel\GA4\Model\Config\Source\ServerSide\TrackingEvents::EVENT_VIEW_ITEM_LIST)
    && $ga4ServerSideHelper->isDataLayerEventDisabled())) : ?>
        <?php $ga4Categories = $helper->getGA4Categories($category); ?>
        <?php $productCollection = $this->getProductCollection(); ?>
        <?php if (count($productCollection)) : ?>
            <?php $categoryProducts = []; ?>
            <?php $i = 1; ?>
            <?php foreach($productCollection as $product) : ?>
                <?php $categoryProduct = []; ?>
                <?php $categoryProduct['item_name'] = $helper->getProductName($product); ?>
                <?php $categoryProduct['affiliation'] = $helper->getAffiliationName(); ?>
                <?php $categoryProduct['item_id'] = $helper->getGtmProductId($product); ?>
                <?php $categoryProduct['price'] = floatval(number_format($product->getPriceInfo()->getPrice('final_price')->getValue(), 2, '.', '')); ?>
                <?php if ($helper->isBrandEnabled()) : ?>
                <?php $categoryProduct['item_brand'] = $helper->getGtmBrand($product); ?>
                <?php endif;?>
                <?php $categoryProduct = array_merge($categoryProduct, $ga4Categories); ?>
                <?php $categoryProduct['item_list_name'] = $gtmCategoryLabel; ?>
                <?php $categoryProduct['item_list_id'] = $category->getId(); ?>
                <?php $categoryProduct['index'] = $i; ?>
                <?php $categoryProducts[] = $categoryProduct; ?>
                <?php $i++ ; ?>
            <?php endforeach; ?>

            <?php
            $this->setImpressionData([
                'items' => $categoryProducts,
                'item_list_id' =>  $category->getId(),
                'item_list_name' => $gtmCategoryLabel
            ]);

            ?>
        <?php endif; ?>
    <?php endif; ?>

    <?php if ($helper->isAdWordsRemarketingEnabled()): ?>
        <?php
            $remarketingData = [];
            $remarketingData['ecomm_pagetype'] = \WeltPixel\GA4\Model\Api\Remarketing::ECOMM_PAGETYPE_CATEGORY;
            $remarketingData['ecomm_category'] = $gtmCategoryLabel;
        ?>
        <?php $this->setDataLayerOption('google_tag_params', $remarketingData); ?>
    <?php endif; ?>
<?php endif; ?>
<?php if ($ga4ServerSideHelper->isServerSideTrakingEnabled() && $ga4ServerSideHelper->shouldEventBeTracked(\WeltPixel\GA4\Model\Config\Source\ServerSide\TrackingEvents::EVENT_VIEW_ITEM_LIST)) : ?>
    <?php $category = $this->getCurrentCategory(); ?>
    <?php $gtmCategoryLabel = $helper->getGtmCategory($category); ?>
    <?php $ga4Categories = $helper->getGA4Categories($category); ?>
    <?php $productCollection = $this->getProductCollection(); ?>
    <?php $categoryProducts = []; ?>
    <?php if (count($productCollection)) : ?>
        <?php $i = 1; ?>
        <?php foreach($productCollection as $product) : ?>
            <?php $categoryProduct = []; ?>
            <?php $categoryProduct['item_name'] = $helper->getProductName($product); ?>
            <?php $categoryProduct['affiliation'] = $helper->getAffiliationName(); ?>
            <?php $categoryProduct['item_id'] = $helper->getGtmProductId($product); ?>
            <?php $categoryProduct['price'] = floatval(number_format($product->getPriceInfo()->getPrice('final_price')->getValue(), 2, '.', '')); ?>
            <?php if ($helper->isBrandEnabled()) : ?>
                <?php $categoryProduct['item_brand'] = $helper->getGtmBrand($product); ?>
            <?php endif;?>
            <?php $categoryProduct = array_merge($categoryProduct, $ga4Categories); ?>
            <?php $categoryProduct['item_list_name'] = $gtmCategoryLabel; ?>
            <?php $categoryProduct['item_list_id'] = $category->getId(); ?>
            <?php $categoryProduct['index'] = $i; ?>
            <?php $categoryProduct['quantity'] = 1; ?>
            <?php $categoryProduct['affiliation'] = $ga4ServerSideHelper->getAffiliationName(); ?>
            <?php
            /** Set the custom dimensions */
            $customDimensions = $this->getProductDimensions($product);
            foreach ($customDimensions as $name => $value) :
                $categoryProduct[$name] = $value;
            endforeach;
            ?>
            <?php $categoryProducts[] = $categoryProduct; ?>
            <?php $i++ ; ?>
        <?php endforeach; ?>
        <?php if (count($categoryProducts)) : ?>
            <?php
                $impressionData = [];
                $impressionData['params'] = [
                    'item_list_id' => $category->getId(),
                    'item_list_name' => $gtmCategoryLabel,
                    'items' => $categoryProducts
                ];
                $this->setServerSideViewItemList($impressionData);
            ?>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
