<?php
// @codingStandardsIgnoreFile
?>
<?php
$_helper = $this->helper('WeltPixel\GA4\Helper\ServerSideTracking');
$parentOrChildUsage = $_helper->getParentOrChildIdUsage();
$isVariantEnabled = $_helper->isVariantEnabled();
if (($parentOrChildUsage == \WeltPixel\GA4\Model\Config\Source\ParentVsChild::CHILD) && $_helper->sendAllChildConfigurableProducts()) {
    $parentOrChildUsage = '';
}
$cspNonceProvider = $_helper->getCspNonceProvider();

?>
<?php if ($_helper->isEnabled()) : ?>
    <script <?php if ($cspNonceProvider) /* @noEscape */ echo ' nonce="' . $cspNonceProvider->generateNonce() . '" ' ?>>
        window.ga4ParentVsChild = '<?php /* @noEscape */ echo $parentOrChildUsage ?>';
        window.ga4VariantEnabled = '<?php /* @noEscape */ echo $isVariantEnabled ?>';
        require(['jquery','weltpixel_ga4_persistentLayer','weltpixel_ga4_gtm', 'Magento_Customer/js/customer-data'],
            function ($, wpGa4PersDl ,wpGa4gtm, customerData) {
                if (window.ga4AllowServices) {
                    $(document).ajaxComplete(function (event, xhr, settings) {
                        if (settings.url.search('/customer\/section\/load/') > 0) {
                            var response = xhr.responseJSON;
                            if (response.wp_ga4) {
                                var dataLayerData = $.parseJSON(response.wp_ga4.datalayer);
                                for (index in dataLayerData) {
                                    window.dataLayer.push({ecommerce: null});
                                    window.dataLayer.push(dataLayerData[index]);
                                }
                            }
                        }
                    });
                    var wpPersDlOptions = {'storageExpiryTime': <?php /* @noEscape */ echo $_helper->getPersistentStorageExpiryTime() ?> };
                    var wpGtmOptions = {
                        'enabled': <?php /* @noEscape */ echo $_helper->trackPromotions() ? '1' : '0' ?>,
                        'persDataLayer': wpGa4PersDl,
                        'disableDatalayerEvents': <?php /* @noEscape */ echo $_helper->isDataLayerEventDisabled() ? '1' : '0' ?>,
                        'serverSidePromotionViewEnabled': <?php /* @noEscape */ echo $_helper->isServerSideTrakingEnabled() && $_helper->shouldEventBeTracked(\WeltPixel\GA4\Model\Config\Source\ServerSide\TrackingEvents::EVENT_VIEW_PROMOTION) ? '1' : '0' ?>,
                        'serverSidePromotionClickEnabled': <?php /* @noEscape */ echo $_helper->isServerSideTrakingEnabled() && $_helper->shouldEventBeTracked(\WeltPixel\GA4\Model\Config\Source\ServerSide\TrackingEvents::EVENT_SELECT_PROMOTION) ? '1' : '0' ?>
                    };
                    wpGa4PersDl.init(wpPersDlOptions);
                    wpGa4gtm.trackPromotion(wpGtmOptions);
                }
            });
    </script>
<?php endif; ?>
