<?php
// @codingStandardsIgnoreFile
/**
 * Usage $this->helper('WeltPixel\GA4\Helper\Data')->addProductClick($_product, $index, 'List Value');
 */
/** @var \WeltPixel\GA4\Helper\ServerSideTracking $ga4ServerSideHelper */
$ga4ServerSideHelper = $this->helper('WeltPixel\GA4\Helper\ServerSideTracking');
/** @var \WeltPixel\GA4\Helper\Data $ga4Helper */
$ga4Helper = $this->helper('WeltPixel\GA4\Helper\Data');
?>

<?php if((!($ga4ServerSideHelper->isServerSideTrakingEnabled() && $ga4ServerSideHelper->shouldEventBeTracked(\WeltPixel\GA4\Model\Config\Source\ServerSide\TrackingEvents::EVENT_SELECT_ITEM)
    && $ga4ServerSideHelper->isDataLayerEventDisabled())) && $this->isEnabled() && $ga4Helper->isDataLayerProductClickEnabled()) : ?>
    <?php $product = $this->getProduct(); ?>
    <?php $helper = $this->helper('WeltPixel\GA4\Helper\Data'); ?>
    <?php if (isset($product)) : ?>
        <?php
        $list = $this->getList();
        $listId = $this->getListId();
        $index = $this->getIndex();
        $productDetail = [];
        $productDetail['item_name'] = $helper->getProductName($product);
        $productDetail['item_id'] = $helper->getGtmProductId($product);
        $productDetail['price'] = floatval(number_format($product->getPriceInfo()->getPrice('final_price')->getValue() ?? 0, 2, '.', ''));
        $productDetail['index'] = $index;
        $ga4Categories = $helper->getGA4CategoriesFromCategoryIds($product->getCategoryIds());
        $productDetail = array_merge($productDetail, $ga4Categories);
        $productDetail['item_list_name'] = $list;
        $productDetail['item_list_id'] = $listId;
         if ($helper->isBrandEnabled()) :
             $productDetail['item_brand'] = $helper->getGtmBrand($product);
         endif;
        /** Set the custom dimensions */
        $customDimensions = $this->getProductDimensions($product, $helper);
        foreach ($customDimensions as $name => $value) :
            $productDetail[$name] = $value;
        endforeach;

        $data = [
            'event' => 'select_item',
            'ecommerce' => [
                'item_list_id' => $listId,
                'item_list_name' => $list,
                'items' => [$productDetail]
             ]
        ];

        ?>
        if (window.ga4AllowServices) {
        window.dataLayer.push({ecommerce: null});
        window.dataLayer.push(<?php echo $this->escapeHtml($this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($data)); ?>);
        }
    <?php endif; ?>
<?php endif; ?>
<?php
if ($ga4ServerSideHelper->isServerSideTrakingEnabled() && $ga4ServerSideHelper->shouldEventBeTracked(\WeltPixel\GA4\Model\Config\Source\ServerSide\TrackingEvents::EVENT_SELECT_ITEM)) :
    $product = $this->getProduct();
    if (isset($product)) :
        $list = $this->getList() ?? '';
        $listId = $this->getListId() ?? '';
        $index = $this->getIndex();
    ?>
        window.wpGA4ServerSide.pushClick(<?= /* @noEscape */ $product->getId() ?>, '<?= /* @noEscape */ addslashes($listId) ?>', '<?=  /* @noEscape */ addslashes(str_replace('"','&quot;', $list)) ?>', <?= /* @noEscape */ $index  ?> , this);
    <?php endif; ?>
<?php endif; ?>
