<div>
    <hr>
    <button id="generate_gtmga4_serverside_api_json" title="<?php echo $block->escapeHtml(__("Generate Json for Variables, Triggers and Tags")) ?>" type="button" class="action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" role="button" aria-disabled="false">
        <span class="ui-button-text"><span><?php echo $block->escapeHtml(__("Generate Server Side Json for Variables, Triggers and Tags")) ?></span></span>
    </button>
    <a id="download_gtmga4_serverside_json" target="_blank" href="<?php echo $block->escapeUrl($this->getUrlForItemsJsonDownload()) ?>" class="action-default scalable  ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" >
        <span class="ui-button-text"><span><?php echo $block->escapeHtml(__("Download Server Side Json")) ?></span></span>
    </a>
    <input type="hidden" value="<?php echo $block->escapeHtmlAttr($block->getFormKey()); ?>" name="api_serverside_form_key" id="api_serverside_form_key" />
</div>
<script>
    requirejs(['jquery', 'WeltPixel_GA4/js/gtmGa4Api' ],
        function   ($, gtmGa4Api) {
            $(document).ready(function() {
                gtmGa4Api.initializeJsonServerSideGeneration('<?php echo $block->escapeUrl($this->getUrlForItemsJsonGeneration()) ?>');
            });
        });
</script>
