<section class="page-main-content">
    <h2>Grey Tones Test</h2>

    <div class="grey-tones-test">
        <h3>Light Grey Stack</h3>

        <div class="theme__white grey-tone-test">
            White
            <div class="theme__light-grey__100 grey-tone-test">
                Light Grey: Lightest
                <div class="theme__light-grey__300 grey-tone-test">
                    Light Grey: Lighter
                    <div class="theme__light-grey__500 grey-tone-test">
                        Light Grey: Light
                        <div class="theme__light-grey__700 grey-tone-test">
                            Light Grey: Dark
                            <div class="theme__light-grey__900 grey-tone-test">
                                Light Grey: Darkest
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        
        <h3>Light Grey Stack - Inverse</h3>

        <div class="theme__light-grey__900 grey-tone-test">
            Light Grey: Darkest
            <div class="theme__light-grey__700 grey-tone-test">
                Light Grey: Darker
                <div class="theme__light-grey__500 grey-tone-test">
                    Light Grey
                    <div class="theme__light-grey__300 grey-tone-test">
                        Light Grey: Light
                        <div class="theme__light-grey__100 grey-tone-test">
                            Light Grey: Lightest
                            <div class="theme__white grey-tone-test">
                                White
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <h3>Dark Grey Stack</h3>

        <div class="theme__black grey-tone-test">
            Black
            <div class="theme__dark-grey__900 grey-tone-test">
                Dark Grey: Darkest
                <div class="theme__dark-grey__700 grey-tone-test">
                    Dark Grey: Darker
                    <div class="theme__dark-grey__500 grey-tone-test">
                        Dark Grey
                        <div class="theme__dark-grey__300 grey-tone-test">
                            Dark Grey: Light
                            <div class="theme__dark-grey__100 grey-tone-test">
                                Dark Grey: Lightest
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <h3>Dark Grey Stack - Inverse</h3>

        <div class="theme__dark-grey__100 grey-tone-test">
            Dark Grey: Darkest
            <div class="theme__dark-grey__300 grey-tone-test">
                Dark Grey: Darker
                <div class="theme__dark-grey__500 grey-tone-test">
                    Dark Grey: Dark
                    <div class="theme__dark-grey__700 grey-tone-test">
                        Dark Grey: Dark
                        <div class="theme__dark-grey__900 grey-tone-test">
                            Dark Grey: Darkest
                            <div class="theme__black grey-tone-test">
                                Black
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="color-tests">
    <div class="color-test">
        <ol class="color-list">
            <li class="theme__theme__primary">
                <div class="color-name">theme__theme__primary</div>
                <div class="color-classname">.theme__theme__primary</div>
                <div class="background-color">BG: <span class="color"></span></div>
                <div class="foreground-color">FG: <span class="color"></span></div>
            </li>

            <li class="theme__theme__primary-alt">
                <div class="color-name">theme__theme__primary-alt</div>
                <div class="color-classname">.theme__theme__primary-alt</div>
                <div class="background-color">BG: <span class="color"></span></div>
                <div class="foreground-color">FG: <span class="color"></span></div>
            </li>
        </ol>
    </div>

    <div class="color-test">
        <ol class="color-list">
            <li class="theme__theme__secondary">
                <div class="color-name">theme__theme__secondary</div>
                <div class="color-classname">.theme__theme__secondary</div>
                <div class="background-color">BG: <span class="color"></span></div>
                <div class="foreground-color">FG: <span class="color"></span></div>
            </li>

            <li class="theme__theme__secondary-alt">
                <div class="color-name">theme__theme__secondary-alt</div>
                <div class="color-classname">.theme__theme__secondary-alt</div>
                <div class="background-color">BG: <span class="color"></span></div>
                <div class="foreground-color">FG: <span class="color"></span></div>
            </li>
        </ol>
    </div>

    <div class="color-test">
        <div class="grey-color-test">
            <ol class="color-list">
                <li class="theme__light-grey__100">
                    <div class="color-name">light-grey__100</div>
                    <div class="color-classname">.theme__light-grey__100</div>
                    <div class="background-color">BG: <span class="color"></span></div>
                    <div class="foreground-color">FG: <span class="color"></span></div>
                </li>
                <li class="theme__light-grey__300">
                    <div class="color-name">light-grey__300</div>
                    <div class="color-classname">.theme__light-grey__300</div>
                    <div class="background-color">BG: <span class="color"></span></div>
                    <div class="foreground-color">FG: <span class="color"></span></div>
                </li>
                <li class="theme__light-grey__500">
                    <div class="color-name">llight-grey__500</div>
                    <div class="color-classname">.theme__light-grey__500</div>
                    <div class="background-color">BG: <span class="color"></span></div>
                    <div class="foreground-color">FG: <span class="color"></span></div>
                </li>
                <li class="theme__light-grey__700">
                    <div class="color-name">light-grey__700</div>
                    <div class="color-classname">.theme__light-grey__700</div>
                    <div class="background-color">BG: <span class="color"></span></div>
                    <div class="foreground-color">FG: <span class="color"></span></div>
                </li>
                <li class="theme__light-grey__900">
                    <div class="color-name">light-grey__900</div>
                    <div class="color-classname">.theme__light-grey__900</div>
                    <div class="background-color">BG: <span class="color"></span></div>
                    <div class="foreground-color">FG: <span class="color"></span></div>
                </li>
            </ol>

            <ol class="color-list">
                <li class="theme__grey">
                    <div class="color-name">grey</div>
                    <div class="color-classname">.theme__grey</div>
                    <div class="background-color">BG: <span class="color"></span></div>
                    <div class="foreground-color">FG: <span class="color"></span></div>
                </li>
            </ol>

            <ol class="color-list">
                <li class="theme__dark-grey__100">
                    <div class="color-name">dark-grey__100</div>
                    <div class="color-classname">.theme__dark-grey__100</div>
                    <div class="background-color">BG: <span class="color"></span></div>
                    <div class="foreground-color">FG: <span class="color"></span></div>
                </li>
                <li class="theme__dark-grey__300">
                    <div class="color-name">dark-grey__300</div>
                    <div class="color-classname">.theme__dark-grey__300</div>
                    <div class="background-color">BG: <span class="color"></span></div>
                    <div class="foreground-color">FG: <span class="color"></span></div>
                </li>
                <li class="theme__dark-grey__500">
                    <div class="color-name">dark-grey__500</div>
                    <div class="color-classname">.theme__dark-grey__500</div>
                    <div class="background-color">BG: <span class="color"></span></div>
                    <div class="foreground-color">FG: <span class="color"></span></div>
                </li>
                <li class="theme__dark-grey__700">
                    <div class="color-name">dark-grey__700</div>
                    <div class="color-classname">.theme__dark-grey__700</div>
                    <div class="background-color">BG: <span class="color"></span></div>
                    <div class="foreground-color">FG: <span class="color"></span></div>
                </li>
                <li class="theme__dark-grey__900">
                    <div class="color-name">dark-grey__900</div>
                    <div class="color-classname">.theme__dark-grey__900</div>
                    <div class="background-color">BG: <span class="color"></span></div>
                    <div class="foreground-color">FG: <span class="color"></span></div>
                </li>
            </ol>
        </div>
    </div>

    <div class="color-test">
        <ol class="color-list">
            <li class="theme__blue__100">
                <div class="color-name">blue__100</div>
                <div class="color-classname">.theme__blue__100</div>
                <div class="background-color">BG: <span class="color"></span></div>
                <div class="foreground-color">FG: <span class="color"></span></div>
            </li>
            <li class="theme__blue__300">
                <div class="color-name">blue__300</div>
                <div class="color-classname">.theme__blue__300</div>
                <div class="background-color">BG: <span class="color"></span></div>
                <div class="foreground-color">FG: <span class="color"></span></div>
            </li>
            <li class="theme__blue__500">
                <div class="color-name">blue__500</div>
                <div class="color-classname">.theme__blue__500</div>
                <div class="background-color">BG: <span class="color"></span></div>
                <div class="foreground-color">FG: <span class="color"></span></div>
            </li>
            <li class="theme__blue__700">
                <div class="color-name">blue__700</div>
                <div class="color-classname">.theme__blue__700</div>
                <div class="background-color">BG: <span class="color"></span></div>
                <div class="foreground-color">FG: <span class="color"></span></div>
            </li>
            <li class="theme__blue__900">
                <div class="color-name">blue__900</div>
                <div class="color-classname">.theme__blue__900</div>
                <div class="background-color">BG: <span class="color"></span></div>
                <div class="foreground-color">FG: <span class="color"></span></div>
            </li>
        </ol>
    </div>


    <div class="color-test">
        <ol class="color-list">
            <li class="theme__green__100">
                <div class="color-name">green__100</div>
                <div class="color-classname">.theme__green__100</div>
                <div class="background-color">BG: <span class="color"></span></div>
                <div class="foreground-color">FG: <span class="color"></span></div>
            </li>
            <li class="theme__green__300">
                <div class="color-name">green__300</div>
                <div class="color-classname">.theme__green__300</div>
                <div class="background-color">BG: <span class="color"></span></div>
                <div class="foreground-color">FG: <span class="color"></span></div>
            </li>
            <li class="theme__green__500">
                <div class="color-name">green__500</div>
                <div class="color-classname">.theme__green__500</div>
                <div class="background-color">BG: <span class="color"></span></div>
                <div class="foreground-color">FG: <span class="color"></span></div>
            </li>
            <li class="theme__green__700">
                <div class="color-name">green__700</div>
                <div class="color-classname">.theme__green__700</div>
                <div class="background-color">BG: <span class="color"></span></div>
                <div class="foreground-color">FG: <span class="color"></span></div>
            </li>
            <li class="theme__green__900">
                <div class="color-name">green__900</div>
                <div class="color-classname">.theme__green__900</div>
                <div class="background-color">BG: <span class="color"></span></div>
                <div class="foreground-color">FG: <span class="color"></span></div>
            </li>
        </ol>
    </div>

    <div class="color-test">
        <ol class="color-list">
            <li class="theme__creamsicle__100">
                <div class="color-name">creamsicle__100</div>
                <div class="color-classname">.theme__creamsicle__100</div>
                <div class="background-color">BG: <span class="color"></span></div>
                <div class="foreground-color">FG: <span class="color"></span></div>
            </li>
            <li class="theme__creamsicle__300">
                <div class="color-name">creamsicle__300</div>
                <div class="color-classname">.theme__creamsicle__300</div>
                <div class="background-color">BG: <span class="color"></span></div>
                <div class="foreground-color">FG: <span class="color"></span></div>
            </li>
            <li class="theme__creamsicle__500">
                <div class="color-name">creamsicle__500</div>
                <div class="color-classname">.theme__creamsicle__500</div>
                <div class="background-color">BG: <span class="color"></span></div>
                <div class="foreground-color">FG: <span class="color"></span></div>
            </li>
            <li class="theme__creamsicle__700">
                <div class="color-name">creamsicle__700</div>
                <div class="color-classname">.theme__creamsicle__700</div>
                <div class="background-color">BG: <span class="color"></span></div>
                <div class="foreground-color">FG: <span class="color"></span></div>
            </li>
            <li class="theme__creamsicle__900">
                <div class="color-name">creamsicle__900</div>
                <div class="color-classname">.theme__creamsicle__900</div>
                <div class="background-color">BG: <span class="color"></span></div>
                <div class="foreground-color">FG: <span class="color"></span></div>
            </li>
        </ol>
    </div>

    <div class="color-test">
        <ol class="color-list">
            <li class="theme__yellow__100">
                <div class="color-name">yellow__100</div>
                <div class="color-classname">.theme__yellow__100</div>
                <div class="background-color">BG: <span class="color"></span></div>
                <div class="foreground-color">FG: <span class="color"></span></div>
            </li>
            <li class="theme__yellow__300">
                <div class="color-name">yellow__300</div>
                <div class="color-classname">.theme__yellow__300</div>
                <div class="background-color">BG: <span class="color"></span></div>
                <div class="foreground-color">FG: <span class="color"></span></div>
            </li>
            <li class="theme__yellow__500">
                <div class="color-name">yellow__500</div>
                <div class="color-classname">.theme__yellow__500</div>
                <div class="background-color">BG: <span class="color"></span></div>
                <div class="foreground-color">FG: <span class="color"></span></div>
            </li>
            <li class="theme__yellow__700">
                <div class="color-name">yellow__700</div>
                <div class="color-classname">.theme__yellow__700</div>
                <div class="background-color">BG: <span class="color"></span></div>
                <div class="foreground-color">FG: <span class="color"></span></div>
            </li>
            <li class="theme__yellow__900">
                <div class="color-name">yellow__900</div>
                <div class="color-classname">.theme__yellow__900</div>
                <div class="background-color">BG: <span class="color"></span></div>
                <div class="foreground-color">FG: <span class="color"></span></div>
            </li>
        </ol>
    </div>

    <div class="color-test">
        <ol class="color-list">
            <li class="theme__red__100">
                <div class="color-name">red__100</div>
                <div class="color-classname">.theme__red__100</div>
                <div class="background-color">BG: <span class="color"></span></div>
                <div class="foreground-color">FG: <span class="color"></span></div>
            </li>
            <li class="theme__red__300">
                <div class="color-name">red__300</div>
                <div class="color-classname">.theme__red__300</div>
                <div class="background-color">BG: <span class="color"></span></div>
                <div class="foreground-color">FG: <span class="color"></span></div>
            </li>
            <li class="theme__red__500">
                <div class="color-name">red__500</div>
                <div class="color-classname">.theme__red__500</div>
                <div class="background-color">BG: <span class="color"></span></div>
                <div class="foreground-color">FG: <span class="color"></span></div>
            </li>
            <li class="theme__red__700">
                <div class="color-name">red__700</div>
                <div class="color-classname">.theme__red__700</div>
                <div class="background-color">BG: <span class="color"></span></div>
                <div class="foreground-color">FG: <span class="color"></span></div>
            </li>
            <li class="theme__red__900">
                <div class="color-name">red__900</div>
                <div class="color-classname">.theme__red__900</div>
                <div class="background-color">BG: <span class="color"></span></div>
                <div class="foreground-color">FG: <span class="color"></span></div>
            </li>
        </ol>
    </div>
</div>