<?php

?>

<main>
    <h1>Heading Level 1</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris malesuada vitae mi id dapibus. Duis id ligula id nibh finibus porta. Suspendisse nec lorem orci. Mauris pellentesque consectetur massa eu facilisis. Aenean at condimentum orci. Nullam at efficitur mauris. Etiam a justo elit. Curabitur non dolor vel elit efficitur posuere vitae eu eros. Nulla vel arcu luctus, maximus mauris id, laoreet lorem. Sed sapien sapien, tempor ac nunc vulputate, varius eleifend ipsum.</p>

    <h2>Heading Level 2</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris malesuada vitae mi id dapibus. Duis id ligula id nibh finibus porta. Suspendisse nec lorem orci. Mauris pellentesque consectetur massa eu facilisis. Aenean at condimentum orci. Nullam at efficitur mauris. Etiam a justo elit. Curabitur non dolor vel elit efficitur posuere vitae eu eros. Nulla vel arcu luctus, maximus mauris id, laoreet lorem. Sed sapien sapien, tempor ac nunc vulputate, varius eleifend ipsum.</p>

    <h3>Heading Level 3</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris malesuada vitae mi id dapibus. Duis id ligula id nibh finibus porta. Suspendisse nec lorem orci. Mauris pellentesque consectetur massa eu facilisis. Aenean at condimentum orci. Nullam at efficitur mauris. Etiam a justo elit. Curabitur non dolor vel elit efficitur posuere vitae eu eros. Nulla vel arcu luctus, maximus mauris id, laoreet lorem. Sed sapien sapien, tempor ac nunc vulputate, varius eleifend ipsum.</p>

    <h4>Heading Level 4</h4>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris malesuada vitae mi id dapibus. Duis id ligula id nibh finibus porta. Suspendisse nec lorem orci. Mauris pellentesque consectetur massa eu facilisis. Aenean at condimentum orci. Nullam at efficitur mauris. Etiam a justo elit. Curabitur non dolor vel elit efficitur posuere vitae eu eros. Nulla vel arcu luctus, maximus mauris id, laoreet lorem. Sed sapien sapien, tempor ac nunc vulputate, varius eleifend ipsum.</p>

    <h5>Heading Level 5</h5>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris malesuada vitae mi id dapibus. Duis id ligula id nibh finibus porta. Suspendisse nec lorem orci. Mauris pellentesque consectetur massa eu facilisis. Aenean at condimentum orci. Nullam at efficitur mauris. Etiam a justo elit. Curabitur non dolor vel elit efficitur posuere vitae eu eros. Nulla vel arcu luctus, maximus mauris id, laoreet lorem. Sed sapien sapien, tempor ac nunc vulputate, varius eleifend ipsum.</p>

    <h6>Heading Level 6</h6>

    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris malesuada vitae mi id dapibus. Duis id ligula id nibh finibus porta. Suspendisse nec lorem orci. Mauris pellentesque consectetur massa eu facilisis. Aenean at condimentum orci. Nullam at efficitur mauris. Etiam a justo elit. Curabitur non dolor vel elit efficitur posuere vitae eu eros. Nulla vel arcu luctus, maximus mauris id, laoreet lorem. Sed sapien sapien, tempor ac nunc vulputate, varius eleifend ipsum.</p>
    <p>Vivamus gravida risus nec tincidunt luctus. Fusce sit amet dui lorem. Morbi fringilla mauris ac ante eleifend, sed euismod orci tristique. Integer lobortis vehicula tellus sit amet bibendum. Nam vel eros a quam vehicula feugiat eget ut ipsum. Morbi vitae metus sapien. Phasellus nec ante quis diam efficitur venenatis. Vestibulum hendrerit leo neque, at vulputate lectus fringilla nec. Ut id metus sed elit malesuada cursus ut nec dolor. Praesent sodales lacus id tempor vestibulum. Ut vitae risus suscipit, auctor metus a, volutpat odio. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut hendrerit enim arcu, in efficitur nisl commodo in. Cras id viverra mi, ac commodo sapien. Pellentesque at augue ac turpis ultrices sodales eget tristique diam.</p>
    <p>Donec porttitor vel ligula in dapibus. Sed facilisis augue a vulputate feugiat. Aenean arcu velit, ultrices vel pellentesque eget, aliquam vel ante. Vestibulum id ipsum a nulla dapibus rutrum vitae in nisi. Nullam vitae bibendum nisi. Donec dignissim urna ut tempus finibus. Aenean sit amet viverra augue, vitae luctus mauris.</p>
    <p>This is a paragraph that contains
        <span>a span</span>,
        <a href="#link">a link</a>,
        <b>bolded text</b>,
        <i>italic text</i>,
        <em>emphasized text</em>,
        <u>underlined text</u>,
        <s>struck-out text</s>
        <mark>marked text</mark>,
        <small>small text</small>,
        text that is<sub>subscripted</sub>,
        text that is<sup>superscripted</sup>,
        abbreviated text (<abbr title="National Aeronautics and Space Administration">NASA</abbr>),
        <span><del>deleted text</del> <ins>replacement text</ins></span>,
        time (<time datetime="2020-08-17 08:00">Monday at 8:00 AM</time>),
        keyboard shortcut indicators <kbd>WIN</kbd>+<kbd>SHIFT</kbd>+<kbd>S</kbd>,
        and <data value="21053">a data tag</data>
    </p>
</main>

<hr>

<p> This is a <q>short quote</q> </p>
<blockquote> This instead is a long quote that is going to use a lot of words and also cite who said that. —<cite>Some People</cite> </blockquote>

<ol>
    <li>Ordered List item</li>
    <li>Ordered List item</li>
    <li>Ordered List item</li>
</ol>

<ul>
    <li>Unordered List item</li>
    <li>Unordered List item</li>
    <li>Unordered List item</li>
</ul>


<h1>Font Vertical Metrics Test</h1>
<?php foreach (['area-normal' => __('Area Normal'), 'joly-display' => __('Joly Display')] as $fontFamily => $fontFamilyLabel): ?>
    <h2><?= $escaper->escapeHtml($fontFamilyLabel) ?></h2>
    <div class="font-vertical-metrics-test" style="font-family: <?= $escaper->escapeHtmlAttr($fontFamily) ?>">
        <div class="ascender-indicator"></div>
        <div class="baseline-indicator"></div>
        <div class="descender-indicator"></div>

        <span class="text">aAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ</span>
    </div>
<?php endforeach ?>

<h1>Font Weight + Style Test</h1>
<?php foreach (['area-normal' => __('Area Normal'), 'joly-display' => __('Joly Display')] as $fontFamily => $fontFamilyLabel): ?>
    <h2><?= $escaper->escapeHtml($fontFamilyLabel) ?></h2>
    <dl style="font-family: <?= $escaper->escapeHtmlAttr($fontFamily) ?>">
        <?php foreach ([100, 200, 300, 400, 500, 600, 700, 800, 900] as $fontWeight): ?>
            <?php foreach (['normal', 'italic'] as $fontStyle): ?>
                <dt><?= $escaper->escapeHtml($fontWeight) ?>, <?= $escaper->escapeHtml($fontStyle) ?></dt>
                <dd style="font-weight: <?= $escaper->escapeHtmlAttr($fontWeight) ?>;font-style: <?= $escaper->escapeHtmlAttr($fontStyle) ?>;">The quick brown fox jumps over the lazy dog</dd>
            <?php endforeach ?>
        <?php endforeach ?>
    </dl>
<?php endforeach ?>


