<?php
/** @var $block \Magento\Sales\Block\Order\Email\Items */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php $_order = $block->getOrder();?>
<?php if ($_order) : ?>
    <table class="email-items">
        <thead>
        <tr>
            <th class="item-info">
                <?= $escaper->escapeHtml(__('Items')) ?>
            </th>
            <th class="item-qty">
                <?= $escaper->escapeHtml(__('Qty')) ?>
            </th>
        </tr>
        </thead>
        <?php foreach ($_order->getAllItems() as $_item) : ?>
            <?php if (!$_item->getParentItem()) : ?>
                <tbody>
                <?= $block->getItemHtml($_item);?>
                </tbody>
            <?php endif; ?>
        <?php endforeach; ?>
    </table>
<?php endif; ?>
