<link href="<?php echo $block->getViewFileUrl('Silk_Coker::css/dragracetires.css'); ?>" rel="stylesheet" type="text/css" />
<?php 
	$referrer = null;
	$from = null; 
?>

<?php
 $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $url = $storeManager->getStore()->getBaseUrl();
?>
<div id="wrapper" class="dragracetires">

    <div class="headers"><!-- start header -->
        <div class="container"><!-- start container -->
            <div class="row"><!-- start row -->
                <div class="header-inn"><!-- start header inn -->
                    <div class="header-left" <?php if($from == 'mandh' || $from == 'phoenix'): ?> style="width:100%;background-size:cover;" <?php endif ?>><!-- start header left -->
                        <?php if($from == 'mandh'): ?>
                            <h2>M&H Drag Tires</h2>
                            <p>mandhdragtires.com has moved to cokertire.com to better serve our online customers.
                                Got questions about drag race tires?
                                Call our drag race tire expert at</p>
                            <h3>1-866-513-2743</h3>
                        <?php elseif($referrer == 'www.dragracetires.com' || $from == 'drt'): ?>
                            <h2>DRAG RACE TIRES</h2>
                            <p>Dragracetires.com has moved to cokertire.com to better serve our online customers.
                                Got questions about drag race tires?
                                Call our drag race tire expert at</p>
                            <h3>1-866-513-2743</h3>
                        <?php elseif($from == 'phoenix'): ?>
                            <h2>PHOENIX RACE TIRES</h2>
                            <p>Phoenixracingtires.com has moved to cokertire.com to better serve our online customers.
                                Got questions about drag race tires?
                                Call our drag race tire expert at</p>
                            <h3>1-866-513-2743</h3>
                        <?php else: ?>
                            <h2>DRAG RACE TIRES</h2>
                            <p>
                                Got questions about drag race tires?
                                Call our drag race tire expert at</p>
                            <h3>1-866-513-2743</h3>
                        <?php endif; ?>
                        <?php switch($from){
                            case 'mandh':
                                $shopbutton = '<a href="'. $url.'tires/brands/m-h-racemaster.html" class="brown-panel-btn">SHOP M&H DRAG TIRES <i class="fa fa-angle-double-right" aria-hidden="true"></i></a>';
                                break;
                            case 'phoenix':
                                $shopbutton = '<a href="'. $url.'tires/brands/phoenix-tires.html" class="brown-panel-btn">SHOP PHOENIX DRAG TIRES <i class="fa fa-angle-double-right" aria-hidden="true"></i></a>';
                                break;
                            default: '';
                                $shopbutton = '<a href="'. $url.'tires/styles/drag-tires.html" class="brown-panel-btn">SHOP DRAG RACE TIRES <i class="fa fa-angle-double-right" aria-hidden="true"></i></a>';
                                break;
                        }
                        echo $shopbutton;
                        ?>
                        <div class="clearfix"></div>
                    </div>
                    <?php if($from == 'mandh' || $from == 'phoenix'): ?>
                        <!-- Don't show links on right for MandH Drag Tires --->
                    <?php else: ?>
                    <div class="header-right"><!-- start header right -->
                        <a href="<?php echo $url; ?>tires/brands/m-h-racemaster.html">
                            <div class="thumb-one"><!-- start thumb one -->
                                <h2>SHOP M&H <br>RACEMASTER <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                                </h2>
                            </div><!-- end thumb one -->
                        </a>
                        <a href="<?php echo $url; ?>tires/brands/phoenix-tires.html">
                            <div class="thumb-two"><!-- start thumb one -->
                                <h2>SHOP PHOENIX <br>RACE TIRES <i class="fa fa-angle-double-right" aria-hidden="true"></i></h2>
                            </div><!-- end thumb one -->
                        </a>
                        <a href="<?php echo $url; ?>tires/styles/drag-tires.html#tire_build=10762">
                            <div class="thumb-three"><!-- start thumb one -->
                                <h2>SHOP Drag <br>Radials <i class="fa fa-angle-double-right" aria-hidden="true"></i></h2>
                            </div><!-- end thumb one -->
                        </a>
                        <div class="clearfix"></div>
                    </div><!-- end header right -->
                    <?php endif ?>
                    <div class="clearfix"></div>
                </div><!-- end header inn -->
            </div><!-- end row -->
        </div><!-- end container -->
    </div><!-- end header -->
    <div class="brown-panel"><!-- start brown-panel -->
        <div class="container"><!-- start container -->
            <div class="row"><!-- start row -->
                <div class="col-sm-6 col-md-6">
                    <img src="<?php echo $block->getViewFileUrl('Silk_Coker::images/dragracetires/tire.png'); ?>" alt="" class="img-responsive tire"/>
                </div>
                <div class="col-sm-6 col-md-6">
                    <h2>Drag Race</h2>
                    <h2>Tire Evolution</h2>
                    <img src="<?php echo $block->getViewFileUrl('Silk_Coker::images/dragracetires/red-title.png'); ?>" alt="" class="red-title"/>
                    <?php if($from == 'mandh'): ?>
                    <p>When M&H Racemaster designed the world’s first purpose-built drag racing slick in 1954, it was a revolutionary tire. But by today’s standards, it doesn’t have much to offer. Now, drag racers can choose from dozens of sizes, styles and compounds, and take advantage of more than 60 years of tire technology.</p>
                    <?php else: ?>
                        <p>When M&H Racemaster designed the world’s first purpose-built drag racing slick in 1954, it was a revolutionary tire. But by today’s standards, it doesn’t have much to offer. Now, drag racers can choose from dozens of sizes, styles and compounds, and take advantage of more than 60 years of tire technology. Dragracetires.com is your source for today’s greatest drag racing tires, offering Phoenix Race Tires and the legendary M&H Racemaster brand. </p>
                    <?php endif ?>
                    <h3>Need drag racing tires?</h3>
                    <h3>Call 1-866-513-2743</h3>
                    <?php echo $shopbutton; ?>
                </div>
            </div><!-- end row -->
        </div><!-- end container -->
    </div>
    <div class="container"><!-- start container-->
        <div class="foot">
        <div class="row" style="padding-bottom: 20px"><!-- start row -->
            <div class="col-sm-5 col-md-4 col-md-offset-1 home-content-left">
                <h2>stick it to the competition</h2>
                <img src="<?php echo $block->getViewFileUrl('Silk_Coker::images/dragracetires/img2.png'); ?>" alt="" class="img-responsive"/>
                <p>Horsepower is a drug that all drag racers are addicted to, and when you find more horsepower, it usually means the next challenge is trying to hook it up on the track. There are a lot of factors that go into planting your horsepower to the ground, and tires are a great place to start. We offer top-of-the-line drag racing tires for many applications, with many compounds and configurations, including lightweight, DOT approved front runner tires. </p>
            </div>
            <div class="col-sm-2 col-md-2">
                <img src="<?php echo $block->getViewFileUrl('Silk_Coker::images/dragracetires/circles.png'); ?>" alt="" class="img-responsive center-block middle-content-img"/>
            </div>
            <div class="col-sm-5 col-md-4 col-md-offset-1 home-content-right">
                <h2>Chassis setup</h2>
                <img src="<?php echo $block->getViewFileUrl('Silk_Coker::images/dragracetires/img3.png'); ?>" alt="" class="img-responsive"/>
                <p>While tires are an important factor in transferring horsepower to the racing surface, you must also pay close attention to the chassis and suspension setup to take full advantage of a sticky tire. Drag cars are built with a widely adjustable suspension, while street cars can be a little more tricky to adjust. Weight balance and weight transfer are the key elements in hooking up on the drag strip, but you have to have a tire that will take the beating. That’s where we come into play!</p>
            </div>
        </div><!-- end row -->
        </div>
    </div><!-- end container -->
    <div class="footer_push"></div>
</div>

