<link href="<?php echo $block->getViewFileUrl('Silk_Coker::css/hdc.css'); ?>" rel="stylesheet" type="text/css" />
<div id="wrapper" class="hdc_landing">
    <div id="content" class="product margin_btm3">
        <div class="container padding_l05r05 margin_btm3">
            <div class="row margin_tb2">
                <img class="img-responsive center-block" src="<?php echo $block->getViewFileUrl('Silk_Coker::images/hdc/hdc_logo.png'); ?>" alt="Hagerty Drivers Club logo">
            </div>
            <div class="row padding0">
                <div class="col-sm-12 padding0 mobile100 mob_pad1 margin_top50">
                    <div class="padding_top1">
                        <div class="page-title margin_btm2">
                            <div class="ronniacondbold uppercase font30 text-center">
                                Welcome Hagerty Drivers Club Member!<br>
                                Your membership allows you a
                            </div>
                            <div class="ronniahvy uppercase bold font72 text-center margin_tb30">
                                10% Discount<br>
                                on Coker Tire's<br>
                                Entire Product Line
                            </div>
                            <div class="ronniacondbold uppercase font36 text-center margin_top1">
                                This discount will show up at checkout.
                            </div>
                            <div class="ronniacond font24 text-center margin_top1">
                                Enjoy your shopping experience with cokertire.com.<br>
                                Thank you for being a Hagerty Drivers Club Member.
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row margin_tb2">
                <a href="/tires.html">
                    <img class="img-responsive center-block" src="<?php echo $block->getViewFileUrl('Silk_Coker::images/hdc/shop_now_btn.png'); ?>" alt="Shop Now">
                </a>
            </div>
        </div>
    </div>
    <div class="footer_push"></div>
</div>