<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_AjaxCart
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Catalog\Block\Product\View\Type\Simple
 */
?>
<?php $product = $block->getProduct(); ?>
<div id="ajax-goto">
    <a class="goto-product" href="<?php echo $block->escapeUrl($product->getUrlModel()->getUrl($product));?>">
        <span><?php echo $block->escapeHtml(__('Go to Product')); ?></span>
    </a>
</div>

<script type="text/x-magento-init">
    {
        "#ajax-goto": {
            "bssGoto": {}
        }
    }
</script>
