sonar.projectKey=cc-industries-project
sonar.projectName=cc-industries-project
sonar.projectVersion=1.0
sonar.language=php
sonar.sources=app/code/I95Dev
sonar.sourceEncoding=UTF-8
sonar.host.url=http://sonar.i95-dev.com