<?php
/**
 * @author i95Dev Team
 * @copyright Copyright (c) 2019 i95Dev(https://www.i95dev.com)
 * @package I95DevConnect_MessageQueue
 */
?>
<div>
    <input type="text" id="check_number" name="payment[check_number]"
    title="<?= /* @noEscape */  $escaper->escapeHtml(__("Cheque Number")) ?>" class="required-entry"
    value=""/>
</div>
<script>
document.getElementById("p_method_checkmo").onclick = enableCheckNumber;

function enableCheckNumber() {
document.getElementById("check_number").disabled = false;
}
</script>
