<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_UrlRewriteImportExport
 * @author     Extension Team
 * @copyright  Copyright (c) 2020 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
// @codingStandardsIgnoreFile

/**
 * @var $block \Bss\UrlRewriteImportExport\Block\Adminhtml\Export\Download
 */
?>
<?php $fileName = $block->getFileNameData(); ?>
<div><?php echo __("Download files: ") ?></div>
<?php foreach ($block->getDirectoryData() as $key => $url): ?>
<a href = "<?php echo $url?>"><?php echo $fileName[$key] ?></a>
<?php endforeach; ?>
<br>
<br>
<br>
