<?php
/**
 * @package Magedelight_Megamenu for Magento 2
 * @author MageDelight Team
 * @copyright Copyright (c) MageDelight (https://www.magedelight.com) owned by Krish TechnoLabs. All Rights reserved.
 */

/** @noinspection PhpComposerExtensionStubsInspection */
/** @noinspection PhpUnhandledExceptionInspection */
/** @var  \Magedelight\Megamenu\Model\MenuItems|\Magedelight\Megamenu\Api\Data\MenuItemsInterface $item */
/** @var  \Magedelight\Megamenu\Block\Topmenu $menuBlock */
/** @var  \Magedelight\Megamenu\Model\MegamenuManagement $menuManagement */
$menuBlock = $block->getData('menu_block');
$item = $block->getData('menu_item');
$menuManagement = $block->getData('menu_management');
$menuId = $block->getData('menu_id');
$liClass = $menuBlock->getActiveClass($item) . ' ' . $item->getItemClass();
$catVerticalMenuBg = $item->getCategoryVerticalMenuBg();
$megaMenuLink = $menuManagement->generateMenuUrl($item) ?: '#';
$megaMenuName = $menuManagement->generateMenuItemName($item);
$catDisplay = $verticalMenu = $menuAdd = false;
$columnCount = 0;
$verticalMenuClass = $rightContentClass = '';
$subcats = [];

if ($menuBlock->getCmsBlockConfig($item, 'left', 'enable') ||
    $menuBlock->getCmsBlockConfig($item, 'right', 'enable')
) {
    $columnCount++;
}
if ($item->getItemType() === 'category' && (int) $item->getCategoryDisplay() === (int) 1) {
    $categoryLoad = $menuManagement->getCategoryById($item->getObjectId());
    $subcats = $menuManagement->getChildrenCategories($categoryLoad);
    if (!empty($subcats)) {
        $catDisplay = true;
        $menuAdd = true;
        if ((int) $item->getCategoryVerticalMenu() === (int) 1) {
            $verticalMenu = true;
            $verticalMenuClass = 'menu-vertical-wrapper';
            $rightContentClass = 'col-menu-3';
        }
    }
}

$openInNewtabText = '';
if ((int) $item->getOpenInNewTab()) {
    $openInNewtabText = 'target="_blank"';
}

if ($menuBlock->getCmsBlockConfig($item, 'left', 'enable') ||
    $menuBlock->getCmsBlockConfig($item, 'right', 'enable') ||
    $menuBlock->getCmsBlockConfig($item, 'header', 'enable') ||
    $menuBlock->getCmsBlockConfig($item, 'bottom', 'enable')
) {
    $catDisplay = true;
}
if ($catDisplay) {
    $liClass .= ' dropdown menu-dropdown-icon category-item nav-' . $item->getItemId();
    if ($verticalMenu) {
        $columnCount = 1;
    } else {
        $columnCount++;
    }
    $menuColumnCount = 1;
    if ($columnCount === 3) {
        $menuColumnCount = $columnCount - 1;
    }
    if ($columnCount === 2) {
        $columnCount++;
    }
    if ($columnCount === 1) {
        $menuColumnCount = 4;
    }
    ?>
    <div class="<?= /* @noEscape */ $liClass ?>" data-item-id="<?=
                                                                /* @noEscape */ $item->getItemId() ?>">
        <ul class="animated <?= /* @noEscape */ $item->getAnimationOption() ?>
        column<?= /* @noEscape */ $columnCount ?> <?= /* @noEscape */ $verticalMenuClass ?>">
            <?php
            if ($menuBlock->getCmsBlockConfig($item, 'header', 'enable')) {
                $cmsClass = "mega-static-block menu-header";
                echo $menuBlock->createCmsBlockHtml(
                    $menuBlock->getCmsBlockConfig($item, 'header', 'block'),
                    $menuBlock->getCmsBlockConfig($item, 'header', 'title'),
                    $cmsClass
                );
            }
            if ($menuBlock->getCmsBlockConfig($item, 'left', 'enable') && !$verticalMenu) {
                $cmsClass = "mega-static-block menu-sidebar-left";
                echo $menuBlock->createCmsBlockHtml(
                    $menuBlock->getCmsBlockConfig($item, 'left', 'block'),
                    $menuBlock->getCmsBlockConfig($item, 'left', 'title'),
                    $cmsClass
                );
            }
            $colClass = $menuBlock->getCmsBlockConfig($item, 'right', 'enable') ? 'col-menu-9' : '';
            ?>
            <li class="mega-static-block menu-content <?= /* @noEscape */ $colClass ?>">
                <?php if (!empty($subcats)) {
                    if ($verticalMenu) { ?>
                        <?= /* @noEscape */ $menuBlock->setVerticalCategoryItem($item, $subcats) ?>
                    <?php } else { ?>
                        <?= /* @noEscape */ $menuBlock->setAllCatChildCategoryColumn(
                            $subcats,
                            $item,
                            $menuId,
                            $menuColumnCount
                        ) ?>
                    <?php } ?>
                <?php } ?>
            </li>
            <?php
            if ($menuBlock->getCmsBlockConfig($item, 'right', 'enable')) {
                $cmsClass = "mega-static-block menu-sidebar-right ' . $rightContentClass . '";
                echo $menuBlock->createCmsBlockHtml(
                    $menuBlock->getCmsBlockConfig($item, 'right', 'block'),
                    $menuBlock->getCmsBlockConfig($item, 'right', 'title'),
                    $cmsClass
                );
            }
            if ($menuBlock->getCmsBlockConfig($item, 'bottom', 'enable')) {
                $cmsClass = "mega-static-block menu-footer";
                echo $menuBlock->createCmsBlockHtml(
                    $menuBlock->getCmsBlockConfig($item, 'bottom', 'block'),
                    $menuBlock->getCmsBlockConfig($item, 'bottom', 'title'),
                    $cmsClass
                );
            }
            ?>
        </ul>
    </div>
<?php } else { ?>
    <div class="<?= /* @noEscape */ $liClass ?>" data-item-id="<?=
                                                                /* @noEscape */ $item->getItemId() ?>">
        <a href="<?= $escaper->escapeUrl($megaMenuLink) ?>" <?= /* @noEscape */ $openInNewtabText ?>>
            <span class="megaitemicons"><?= /* @noEscape */ $item->getItemFontIcon() ?></span>
            <?= $escaper->escapeHtml(__($megaMenuName)) ?>
        </a>
    </div>
<?php } ?>
