<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_UrlRewriteImportExport
 * @author     Extension Team
 * @copyright  Copyright (c) 2020 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
// @codingStandardsIgnoreFile
/** @var $block \Magento\Backend\Block\Widget\Form */
?>
<?php /* @todo replace .form-inline with better class name */?>
<?php /* ToDo UI: check if we need this wrapper in the process of global forms refactoring */ ?>

<div class="entry-edit form-inline">
    <?= $block->getFormHtml() ?>
</div>
<?= $block->getChildHtml('form_after') ?>
<?= $block->getChildHtml('form_script') ?>
