<?php
// @codingStandardsIgnoreFile
/** @var $block \WeltPixel\GA4\Block\MetaPixel\Common */

/** @var \Magento\CatalogSearch\Helper\Data $searchDataHelper */
$searchDataHelper = $this->helper('Magento\CatalogSearch\Helper\Data');
/** @var \WeltPixel\GA4\Helper\MetaPixelTracking $metaPixelHelper */
$metaPixelHelper = $this->helper('WeltPixel\GA4\Helper\MetaPixelTracking');
$cspNonceProvider = $metaPixelHelper->getCspNonceProvider();
$searhString = $searchDataHelper->getEscapedQueryText();
$eventId = $metaPixelHelper->getEventUID();
?>
<?php if ($block->isMetaPixelTrackingEnabled() && $block->shouldMetaPixelEventBeTracked(\WeltPixel\GA4\Model\Config\Source\MetaPixel\TrackingEvents::EVENT_SEARCH)) : ?>
<script  <?php if ($cspNonceProvider) /* @noEscape */ echo ' nonce="' .  $cspNonceProvider->generateNonce() . '" ' ?>>
    if (window.ga4AllowServices) {
        fbq('track', 'Search', {
            search_string: '<?=  /* @noEscape */ $searhString ?>'
        },{
            eventID: '<?= /* @noEscape */$eventId ?>'
        });
    }
</script>
<?php endif; ?>

<?php if ($metaPixelHelper->isServerSideTrackingEnabled() && $metaPixelHelper->shouldMetaServerSideEventBeTracked(\WeltPixel\GA4\Model\Config\Source\MetaPixel\TrackingEvents::EVENT_SEARCH)) : ?>
    <script  <?php if ($cspNonceProvider) /* @noEscape */ echo ' nonce="' .  $cspNonceProvider->generateNonce() . '" ' ?>>
        requirejs(['jquery'],
            function  ($) {
                $(document).ready(function() {
                    var requestUrl = '<?php echo $block->escapeUrl($metaPixelHelper->getMetaSSTrackUrl()); ?>';
                    $.post({
                        url: requestUrl,
                        global: false,
                        data: {
                            'eventID': '<?= /* @noEscape */ $eventId ?>',
                            'eventName': 'Search',
                            'eventIdentifier': '<?= /* @noEscape */ \WeltPixel\GA4\Model\Config\Source\MetaPixel\TrackingEvents::EVENT_SEARCH  ?>',
                            'eventUrl': '<?= $block->escapeUrl($metaPixelHelper->getStoreCurrenUrl()) ?>',
                            'searchString': '<?=  /* @noEscape */  $searhString ?>'
                        }
                    });
                });
            });
    </script>
<?php endif; ?>
