<?php
/**
 * @author i95Dev Team
 * @copyright Copyright (c) 2019 i95Dev(https://www.i95dev.com)
 * @package I95DevConnect_MessageQueue
 */
// @codingStandardsIgnoreFile
use Magento\Framework\App\ObjectManager;

$totalrecords = $this->getEntityWiseSyncReport();
$summaryClass = 'I95DevConnect\MessageQueue\Block\Adminhtml\Summary';
$entityCode = 'entity_code=';
?>
<table class="data-grid" id="warehouse_code_table">
    <caption>&nbsp;</caption>
    <thead>
        <tr>
            <th data-sort="entity"  class="data-grid-th _sortable not-sort  col-entity" style="width: 200px;"><span>Entity</span></th>
            <th data-sort="pending"  class="data-grid-th _sortable not-sort  col-pending"><span>Pending</span></th>
            <th data-sort="processing" class="data-grid-th _sortable not-sort  col-processing"><span>Processing</span></th>
            <th data-sort="error" class="data-grid-th _sortable not-sort  col-error"><span>Error</span></th>
            <th data-sort="success"  class="data-grid-th _sortable not-sort  col-success"><span>Success</span></th>
            <th data-sort="complete" class="data-grid-th _sortable not-sort  col-complete"><span>Complete</span></th>
            <th data-sort="total" class="data-grid-th _sortable not-sort  col-total"><span>Total by Entity</span></th>
        </tr>
    </thead>
    <tbody>
        <?php
        if (count($totalrecords) > 0) {
            $statusData = [
                "pending" => 1,
                "processing" => 2,
                "error" => 3,
                "success" => 4,
                "complete" => 5
            ];
            foreach ($totalrecords as $record) {
                $entity = str_replace(' ', '_', $record['entity_code']);
                ?>
                <tr class="">
                    <td class=" col-entity">
                        <strong> <?= /* @noEscape */  $record['entity']; ?> </strong>
                    </td>

                    <?php
                    foreach($statusData as $statusText => $statusCode) {
                    ?>
                    <td class=" col-id col-" <?php echo __($statusText); ?>>
                        <?php
                        $objectManager = ObjectManager::getInstance();
                        $storeManager = $objectManager->get($summaryClass);
                        $adminUrl = $storeManager->getInboundMessageQueue();
                        ?>
                        <a href="<?= /* @noEscape */  $block->getMessageQUrl($entityCode . $entity . '&' . 'status=' . $statusCode); ?>"> <?= /* @noEscape */  $record[$statusText]; ?>  </a>
                    </td>
                    <?php
                    }
                    ?>
                    <td class=" col-id col-processing">
                        <?= /* @noEscape */  $record['total']; ?>
                    </td>
                </tr>
                <?php
                $totalstatuscount = $this->getTotalStatusRcords();
            }
            ?>
            <tr>
                <td><strong>Total by Status</strong></td>
                <td><strong> <?= /* @noEscape */  $totalstatuscount['pending']; ?>   </strong></td>
                <td><strong> <?= /* @noEscape */  $totalstatuscount['processing']; ?>   </strong></td>
                <td><strong><?= /* @noEscape */  $totalstatuscount['error']; ?> </strong></td>
                <td><strong><?= /* @noEscape */  $totalstatuscount['success']; ?> </strong></td>
                <td><strong><?= /* @noEscape */  $totalstatuscount['complete']; ?> </strong></td>
                <td><strong><?= /* @noEscape */  $totalstatuscount['total']; ?> </strong></td>

            </tr>
        <?php
        } else { ?>
            <tr>
                <td colspan="7" style="text-align: center "><strong> No Records Found </strong></td>
            </tr>
        <?php
        } ?>
    </tbody>
</table>
<script>
    require([ 'jquery', 'mage/url' ], function ($, url)
    {
        window.location.replace(url.build('messagequeue/messagequeue/'));
    }
</script>