<?php

namespace Crimson\CokerWV\Service;

use Crimson\CokerWV\Api\CokerStoreInterface;
use Crimson\CokerWV\Api\WVStoreInterface;
use Magento\Framework\App\Filesystem\DirectoryList;
use Magento\Framework\Exception\LocalizedException;
use Magento\Framework\Filesystem\Driver\File;
use Magento\Store\Api\StoreRepositoryInterface;
use Amasty\SeoToolkitLite\Api\Data\RedirectInterfaceFactory;
use Amasty\SeoToolkitLite\Api\RedirectRepositoryInterface;
use Amasty\PromoBanners\Model\RuleFactory;

class ImportAmastySeoRedirect
{

    const CSV_FILE_PATH = '/import/coker_zip_data_migration/amasty_seotoolkit_redirect.json';

    public function __construct(
        private readonly DirectoryList            $directoryList,
        private readonly File                     $file,
        private readonly StoreRepositoryInterface $storeRepositoryInterface,
        private readonly RedirectRepositoryInterface $redirectRepository,
        private readonly RedirectInterfaceFactory $redirectInterfaceFactory
    )
    {
    }


    public function execute(): array
    {
        $result['message'] = "All Amasty SEO toolkit redirect entires imported.";
        try {
            $csvPath = $this->directoryList->getPath(DirectoryList::VAR_DIR) . self::CSV_FILE_PATH;
            if (!$this->file->isExists($csvPath)) {
                throw new \Exception("Error with the JSON file.");
            }

            $rows = json_decode($this->file->fileGetContents($csvPath));
        } catch (\Exception $e) {
            $result['message'] = $e->getMessage();
            return $result;
        }

        $cokerTireStoreId = $this->storeRepositoryInterface->get(CokerStoreInterface::COKER_STORE_CODE)->getId();
        $wvStoreId = $this->storeRepositoryInterface->get(WVStoreInterface::WV_STORE_CODE)->getId();

        // looping
        foreach ($rows as $key => $row) {

            /** @var \Amasty\SeoToolkitLite\Api\Data\RedirectInterface $redirect */
            $redirect = $this->redirectInterfaceFactory->create();
            $redirect->setStatus($row->status)
                ->setRequestPath($row->request_path)
                ->setTargetPath($row->target_path)
                ->setRedirectType($row->redirect_type)
                ->setPriority($row->priority)
                ->setUndefinedPageOnly(0)
                ->setIsAutogenerated(0);
            $redirect->setIsTargetPathExternal($row->is_target_path_external);
            $redirect->setData('store_ids',[$cokerTireStoreId,$wvStoreId]);
            try {
                //creating and saving
                $this->redirectRepository->save($redirect);
            }
            catch (\Exception $e){
                throw $e;
            }
        }

        return $result;
    }
}
