<?php
/**
 * @author i95Dev Team
 * @copyright Copyright (c) 2019 i95Dev(https://www.i95dev.com)
 * @package I95DevConnect_DiscountGroups
 */

use Magento\Framework\App\ObjectManager;

// phpcs:ignoreFile
?>
<?php
$_items = $block->getItems();
$objectManager = ObjectManager::getInstance();
$dgHelper = $objectManager->create('I95DevConnect\DiscountGroups\Helper\Data');
$isenable = $dgHelper->isDiscountGroupsEnabled();
?>
<?php if (empty($_items)): ?>
    <div id="order-items_grid">
        <div class="admin__table-wrapper">
            <table class="data-table admin__table-primary order-tables">
                <thead>
                    <tr class="headings">
                        <th class="col-product"><span><?= /* @noEscape */  __('Product') ?></span></th>
                        <th class="col-price"><span><?= /* @noEscape */  __('Price') ?></span></th>
                        <th class="col-qty"><span><?= /* @noEscape */  __('Qty') ?></span></th>
                        <th class="col-subtotal"><span><?= /* @noEscape */  __('Subtotal') ?></span></th>
                        <th class="col-discount"><span><?= /* @noEscape */  __('Discount') ?></span></th>
                        <?php if ($isenable) { ?>
                        <th class="col-discount-group"><span><?= /* @noEscape */  __('Discount Group Amount') ?></span></th>
                        <?php } ?>
                        <th class="col-row-total"><span><?= /* @noEscape */  __('Row Subtotal') ?></span></th>
                        <th class="col-action"><span><?= /* @noEscape */  __('Action') ?></span></th>
                    </tr>
                </thead>
                <tbody>
                    <tr class="even">
                        <td class="empty-text" colspan="100"><?= /* @noEscape */  __('No ordered items') ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
<?php else: ?>
    <div class="admin__table-wrapper" id="order-items_grid">
    <?php if (count($_items)>10): ?>
        <div class="actions update actions-update">
            <?= /* @noEscape */  $block->getButtonHtml(__('Update Items and Quantities'), 'order.itemsUpdate()', 'action-secondary'); ?>
        </div>
    <?php endif; ?>
        <table class="data-table admin__table-primary order-tables">
            <thead>
                <tr class="headings">
                    <th class="col-product"><span><?= /* @noEscape */  __('Product') ?></span></th>
                    <th class="col-price"><span><?= /* @noEscape */  __('Price') ?></span></th>
                    <th class="col-qty"><span><?= /* @noEscape */  __('Qty') ?></span></th>
                    <th class="col-subtotal"><span><?= /* @noEscape */  __('Subtotal') ?></span></th>
                    <th class="col-discount"><span><?= /* @noEscape */  __('Discount') ?></span></th>
                    <?php if ($isenable) { ?>
                    <th class="col-discount-group"><span><?= /* @noEscape */  __('Discount Group Amount') ?></span></th>
                    <?php } ?>
                    <th class="col-row-total"><span><?= /* @noEscape */  __('Row Subtotal') ?></span></th>
                    <th class="col-action"><span><?= /* @noEscape */  __('Action') ?></span></th>
                </tr>
            </thead>
                <?php $i = 0;
                $totalDiscountGroupAmount = 0; ?>
                <tbody class="<?= /* @noEscape */ ($i%2) ? 'even' : 'odd' ?>">
                <?php foreach ($_items as $_item):$i++ ?>
                    <tr>
                        <td class="col-product">
                            <span id="order_item_<?= /* @noEscape */  $_item->getId() ?>_title"><?= /* @noEscape */  $block->escapeHtml($_item->getName()) ?></span>
                            <div class="product-sku-block">
                                <span><?= /* @noEscape */  __('SKU') ?>:</span>
                                <?= /* @noEscape */  implode('<br />', $this->helper(Magento\Catalog\Helper\Data::class)->splitSku($block->escapeHtml($_item->getSku()))); ?>
                            </div>
                            <div class="product-configure-block">
                                <?= /* @noEscape */  $block->getConfigureButtonHtml($_item) ?>
                            </div>
                        </td>
                        <td class="col-price">
                            <?= /* @noEscape */  $block->formatPrice($_item->getPrice()) ?>
                            <?php $_isCustomPrice = $block->usedCustomPriceForItem($_item) ?>
                            <?php if ($_tier = $block->getTierHtml($_item)): ?>
                            <div id="item_tier_block_<?= /* @noEscape */  $_item->getId() ?>"<?php if ($_isCustomPrice): ?> style="display:none"<?php endif; ?>>
                                <a href="#" onclick="$('item_tier_<?= /* @noEscape */  $_item->getId() ?>').toggle();return false;"><?= /* @noEscape */  __('Tier Pricing') ?></a>
                                <div style="display:none" id="item_tier_<?= /* @noEscape */  $_item->getId() ?>"><?= /* @noEscape */  $_tier ?></div>
                            </div>
                            <?php endif; ?>
                            <?php if ($block->canApplyCustomPrice($_item)): ?>
                                <div class="custom-price-block">
                                    <input type="checkbox"
                                           class="admin__control-checkbox"
                                           id="item_use_custom_price_<?= /* @noEscape */  $_item->getId() ?>"
                                           <?php if ($_isCustomPrice): ?> checked="checked"<?php endif; ?>
                                           onclick="order.toggleCustomPrice(this, 'item_custom_price_<?= /* @noEscape */  $_item->getId() ?>', 'item_tier_block_<?= /* @noEscape */  $_item->getId() ?>');"/>
                                    <label
                                        class="normal admin__field-label"
                                        for="item_use_custom_price_<?= /* @noEscape */  $_item->getId() ?>">
                                        <span><?= /* @noEscape */  __('Custom Price') ?>*</span></label>
                                </div>
                            <?php endif; ?>
                            <input id="item_custom_price_<?= /* @noEscape */  $_item->getId() ?>"
                                   name="item[<?= /* @noEscape */  $_item->getId() ?>][custom_price]"
                                   value="<?= /* @noEscape */  sprintf("%.2f", $block->getOriginalEditablePrice($_item))?>"
                                   <?php if (!$_isCustomPrice): ?>
                                   style="display:none"
                                   disabled="disabled"
                                   <?php endif; ?>
                                   class="input-text item-price admin__control-text"/>
                        </td>
                        <td class="col-qty">
                            <input name="item[<?= /* @noEscape */  $_item->getId() ?>][qty]"
                                   class="input-text item-qty admin__control-text"
                                   value="<?= /* @noEscape */  $_item->getQty()*1 ?>"
                                   maxlength="12" />
                        </td>
                        <td class="col-subtotal col-price">
                            <?= /* @noEscape */  $block->formatPrice($_item->getRowTotal()) ?>
                        </td>
                        <td class="col-discount col-price">
                            <?= /* @noEscape */  $block->formatPrice(-$_item->getTotalDiscountAmount()) ?>
                            <div class="discount-price-block">
                                <input id="item_use_discount_<?= /* @noEscape */  $_item->getId() ?>"
                                       class="admin__control-checkbox"
                                       name="item[<?= /* @noEscape */  $_item->getId() ?>][use_discount]"
                                       <?php if (!$_item->getNoDiscount()): ?>checked="checked"<?php endif; ?>
                                       value="1"
                                       type="checkbox" />
                                <label
                                    for="item_use_discount_<?= /* @noEscape */  $_item->getId() ?>"
                                    class="normal admin__field-label">
                                    <span><?= /* @noEscape */  __('Apply') ?></span></label>
                            </div>

                        </td>
                        <?php
                        if ($isenable) {
                            $totalDiscountGroupAmount += $_item->getDiscountGroupAmount(); ?>
                        <td class="col-discount-group col-price">
                            <?= /* @noEscape */  $block->formatPrice($_item->getDiscountGroupAmount()) ?>
                        </td>
                        <?php
                        } ?>
                        <td class="col-price col-row-subtotal">
                            <?= /* @noEscape */  $block->formatPrice($_item->getRowTotal()-$_item->getDiscountAmount()+$_item->getDiscountGroupAmount()) ?>
                        </td>
                        <td class="col-actions last">
                            <select class="admin__control-select" name="item[<?= /* @noEscape */  $_item->getId() ?>][action]">
                                <option value=""><?= /* @noEscape */  __('Please select') ?></option>
                                <option value="remove"><?= /* @noEscape */  __('Remove') ?></option>
                                <?php if ($block->getCustomerId() && $block->getMoveToCustomerStorage()): ?>
                                    <option value="cart"><?= /* @noEscape */  __('Move to Shopping Cart') ?></option>
                                    <?php if ($block->isMoveToWishlistAllowed($_item)): ?>
                                        <?php $wishlists = $block->getCustomerWishlists();?>
                                        <?php if (count($wishlists) <= 1):?>
                                            <option value="wishlist"><?= /* @noEscape */  __('Move to Wish List') ?></option>
                                        <?php else: ?>
                                            <optgroup label="<?= /* @noEscape */  __('Move to Wish List') ?>">
                                                <?php foreach ($wishlists as $wishlist):?>
                                                    <option value="wishlist_<?= /* @noEscape */  $wishlist->getId();?>"><?= /* @noEscape */  $block->escapeHtml($wishlist->getName());?></option>
                                                <?php endforeach;?>
                                            </optgroup>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </select>
                        </td>
                    </tr>

                    <?php $hasMessageError = false; ?>
                    <?php foreach ($_item->getMessage(false) as $messageError):?>
                        <?php if (!empty($messageError)) {
                            $hasMessageError = true;
                        }
                        ?>
                    <?php endforeach; ?>

                    <?php if ($hasMessageError):?>
                        <tr class="row-messages-error">
                            <td colspan="100"> <!-- ToDo UI: remove the 100 -->
                                <?php foreach ($_item->getMessage(false) as $message):
                                    if (empty($message)) {
                                        continue;
                                    }
                                    ?>
                                    <div class="message <?php if ($_item->getHasError()): ?>message-error<?php else: ?>message-notice<?php endif; ?>">
                                        <?= /* @noEscape */  $block->escapeHtml($message); ?>
                                    </div>
                                <?php endforeach; ?>
                            </td>
                        </tr>
                    <?php endif;?>

                    <?= /* @noEscape */  $block->getItemExtraInfo($_item)->toHtml(); ?>
                <?php endforeach; ?>
            </tbody>
            
            <tfoot>
                <tr>
                    <td class="col-total"><?= /* @noEscape */  __('Total %1 product(s)', count($_items)) ?></td>
                    <td colspan="2" class="col-subtotal"><?= /* @noEscape */  __('Subtotal:') ?></td>
                    <td class="col-price"><strong><?= /* @noEscape */  $block->formatPrice($block->getSubtotal()) ?></strong></td>
                    <td class="col-price"><strong><?= /* @noEscape */  $block->formatPrice($block->getDiscountAmount()) ?></strong></td>
                    <td class="col-price"><strong><?= /* @noEscape */  $block->formatPrice($totalDiscountGroupAmount) ?></strong></td>
                    <td class="col-price"><strong>
                    <?=
                        /* @noEscape */ $block->formatPrice($block->getSubtotalWithDiscount() + $totalDiscountGroupAmount);
                    ?></strong></td>
                    <td colspan="2">&nbsp;</td>
                </tr>
            </tfoot>
        </table>
        <p><small><?= /* @noEscape */  $block->getInclExclTaxMessage(); ?></small></p>
    </div>

    <div class="order-discounts">
        <?=
        /* @noEscape */  $block->getButtonHtml(__('Update Items and Quantities'), 'order.itemsUpdate()', 'action-secondary');
        ?>
        <div id="order-coupons" class="order-coupons"><?= /* @noEscape */  $block->getChildHtml();?></div>
    </div>

    <script>
        require([
            'Magento_Sales/order/create/form'
        ], function(){
            order.itemsOnchangeBind()
        });
    </script>

    <?php if ($block->isGiftMessagesAvailable()): ?>
<script>
require([
    "prototype",
    "Magento_Sales/order/giftoptions_tooltip"
], function(){

//<![CDATA[
    /**
     * Retrieve gift options tooltip content
     */
    function getGiftOptionsTooltipContent(itemId) {
        var contentLines = [];
        var headerLine = null;
        var contentLine = null;

        $$('#gift_options_data_' + itemId + ' .gift-options-tooltip-content').each(function (element) {
            if (element.down(0)) {
                headerLine = element.down(0).innerHTML;
                contentLine = element.down(0).next().innerHTML;
                if (contentLine.length > 30) {
                    contentLine = contentLine.slice(0,30) + '...';
                }
                contentLines.push(headerLine + ' ' + contentLine);
            }
        });
        return contentLines.join('<br/>');
    }

    giftOptionsTooltip.setTooltipContentLoaderFunction(getGiftOptionsTooltipContent);

    window.getGiftOptionsTooltipContent = getGiftOptionsTooltipContent;

//]]>

});
</script>
    <?php endif; ?>
<?php endif; ?>
