<?php
/**
 * @var $block \Magento\Catalog\Block\Product\View
 */
/** @var \WeltPixel\GA4\Helper\ServerSideTracking $ga4Helper */
$ga4Helper = $this->helper('WeltPixel\GA4\Helper\ServerSideTracking');
$cspNonceProvider = $ga4Helper->getCspNonceProvider();
?>
<?php
if ($ga4Helper->isServerSideTrakingEnabled() && $ga4Helper->shouldEventBeTracked(\WeltPixel\GA4\Model\Config\Source\ServerSide\TrackingEvents::EVENT_VIEW_ITEM)) :
$product = $block->getProduct();
?>
<script  <?php if ($cspNonceProvider) /* @noEscape */ echo ' nonce="' .  $cspNonceProvider->generateNonce() . '" ' ?>>
    requirejs(['jquery'],
        function   ($) {
            $(document).ready(function() {
                var requestUrl = '<?php echo $block->escapeUrl($this->getUrl("weltpixel_ga4/track/product/")); ?>';
                $.post({
                    url: requestUrl,
                    global: false,
                    data: {
                        'product_id': '<?= /* @noEscape */ $product->getId()?>',
                        'product_type': '<?= /* @noEscape */ $product->getTypeId() ?>'
                    }
                });
            });
        });
</script>
<?php endif; ?>
