<?php
$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
?>

<?= /* @noEscape */  $block->getGridHtml(); ?>
<input type="hidden" name="product_assign" id="in_category_products" data-form-part="magedelight_megamenu_label_form" value="" />
<script type="text/x-magento-init">
    {
        "*": {
            "Magedelight_Megamenu/products/assign-products": {
                "selectedProducts": <?= /* @noEscape */ $block->getProductsJson(); ?>,
                "gridJsObjectName": <?= /* @noEscape */ '"'. $gridJsObjectName . '"' ?: '{}'; ?>
            }
        }
    }
</script>
<!-- @todo remove when "UI components" will support such initialization -->
<script>
    require('mage/apply/main').apply();
</script>