<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_ImportExportCore
 * @author     Extension Team
 * @copyright  Copyright (c) 2022 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

/**
 * @var Bss\ImportExportCore\Block\Adminhtml\ImportProcessPage $block
 */
?>

<div class="messages">
    <div class="message message-success success">
        <div data-ui-id="magento-framework-view-element-messages-0-message-success"><?php echo $block->getProcess()?></div>
    </div>
    <div class="message message-notice notice">
        <div data-ui-id="magento-framework-view-element-messages-0-message-notice" >
            <strong>Check var/importexport/bss_processing For More Information</strong>
            <br>
        </div>
    </div>
</div>
