<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var \Magento\VisualMerchandiser\Block\Adminhtml\Category\Merchandiser $block */ ?>
<div id="merchandiser-app" class="merchandiser-app" data-role="merchandiser-app">
    <div id="regular-product-settings" class="regular-category-settings">
        <div class="actions">
            <?= $block->getChildHtml('add_products_button') ?>
        </div>
    </div>
    <div class="merchandiser-tabs" data-role="merchandiser-tabs">
        <ul role="tablist" class="tabs">
            <li role="tab">
                <a href="#tab_grid" id="mode-grid" class="modes-mode mode-grid" data-role="mode-switcher" data-value="grid" title="<?= $escaper->escapeHtmlAttr(__('Grid')) ?>">
                    <span><?= $escaper->escapeHtml(__('Grid')) ?></span>
                </a>
            </li>
            <li role="tab">
                <a href="#tab_tile" id="mode-tile" class="modes-mode mode-tile" data-role="mode-switcher" data-value="tile" title="<?= $escaper->escapeHtmlAttr(__('Tile')) ?>">
                    <span><?= $escaper->escapeHtml(__('Tile')) ?></span>
                </a>
            </li>
        </ul>

        <div id="tab_grid" class="tabs-tab-grid merchandiser-tab" role="tabpanel">
            <?= $block->getChildHtml('grid') ?>
        </div>
        <div id="tab_tile" class="tabs-tab-tile merchandiser-tab" role="tabpanel">
            <?= $block->getChildHtml('tile') ?>
        </div>
        <div class="no-display">
            <input type="hidden" data-form-part="img_document_form" name="vm_document_products" id="vm_document_products" value="<?= $escaper->escapeHtmlAttr($block->getPositionDataJson()) ?>" />
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "[data-role=merchandiser-app]": {
            "Silk_ProductImage/js/merchandiser": {
                "addProductsUrl": "<?= $escaper->escapeJs($escaper->escapeUrl($block->getDialogUrl())) ?>",
                "savePositionsUrl": "<?= $escaper->escapeJs($escaper->escapeUrl($block->getSavePositionsUrl())) ?>",
                "getPositionsUrl": "<?= $escaper->escapeJs($escaper->escapeUrl($block->getProductsPositionsUrl())) ?>",
                "currentDocumentId": "<?= $escaper->escapeJs($block->getDocumentId()) ?>",
                "positionCacheKey": "<?= $escaper->escapeJs($block->getPositionCacheKey()) ?>",
                "positionCacheKeyName": "<?= $escaper->escapeJs($block->getPositionCacheKeyName()) ?>",
                "formName": "img_document_form"
            }
        }
    }
</script>
<!-- @todo remove when "UI components" will support such initialization -->
<script>
    require('mage/apply/main').apply();
</script>
