<?php $size = $block->getSize(); ?>
    <div class="block filter">
        <div class="block-title filter-title">
            <strong><?php /* @escapeNotVerified */ echo __('Search By') ?><i class="glyphicon glyphicon-triangle-right"></i></strong>
        </div>
        <div class="block-content filter-content">
        <ol class="items">
        <li class="item am_shopby_state_container" data-container="cat" data-value="411352">
        <span class="filter-value"><strong> Size::<?php echo $size; ?></strong></span>
        </li>
        </ol>
        </div>
    </div>

