<?php
/** @var \Crimson\LoginRegisterModal\Block\Form\Login $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<div class="block block-customer-login" id="popup-modal" style="display:none;">
    <div class="block-title form-heading">
        <h5 class="block-customer-login-heading" role="heading" aria-level="2">Zip Corvette Log In</h5>
    </div>
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-customer-login"
              action="<?= $escaper->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
                  <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login" data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>">

                <div class="messages">
                    <div class="message message-error error">
                        <div>Invalid login or password.</div>
                    </div>
                </div>

                <div class="field email required">
                    <label class="label" for="email"><span><?= $escaper->escapeHtml(__('Email')) ?></span></label>
                    <div class="control">
                        <input name="username" value="" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?= $escaper->escapeHtmlAttr(__('Email')) ?>" data-validate="{required:true, 'validate-email':true}" placeholder="Email Address">
                    </div>
                </div>
                <div class="field password required">
                    <label for="pass" class="label"><span><?= $escaper->escapeHtml(__('Password')) ?></span></label>
                    <div class="control">
                        <input name="password" type="password" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?= $escaper->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}" placeholder="Password">
                    </div>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
                <div class="actions-toolbar">
                    <div class="main-login-forgot">
                        <a class="action remind" href="<?= $escaper->escapeUrl($block->getForgotPasswordUrl()) ?>"><?= $escaper->escapeHtml(__('Forgot Password?')) ?></a>
                    </div>
                    <div class="main-login-btn">
                        <button type="submit" class="action login primary action-login" name="submit" id="send2">Login</button>
                    </div>
                </div>
            </fieldset>

        </form>
    </div>
</div>

<script>

    var SignInModal = {};

    require([
        'jquery',
        'Magento_Ui/js/modal/modal',
        'domReady!'
    ], function ($, modal) {
        $(function () { // to ensure that code evaluates on page load
            var loginOptions = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                focus: '.block-title',
                modalClass: 'custom-block-customer-login',
                buttons: false
            };

            var headerElem = $('.header.content');
            var accountMenu = headerElem.find('.account-menu');
            var loginLink = headerElem.find('a.log-in');

            loginLink.click(function(e){
                e.preventDefault();
                accountMenu.off();
            });

            if ($('#popup-modal').length > 0) {
                modal(loginOptions, $('#popup-modal'));
            }

            loginLink.on('click', function (e) {
                e.preventDefault();
                $('#popup-modal').modal("openModal");
            });

            SignInModal.open = function () {
                $('#popup-modal').modal("openModal");
            };
        });
    });
</script>

<script type="text/x-magento-init">
{
    "*": {
        "crimson_login":
            {

            }
    }
}
</script>

<style>
    .form-customer-login .messages .message {
        display: none;
    }
</style>
