<?php
// @codingStandardsIgnoreFile
/** @var $block \WeltPixel\GA4\Block\TiktokPixel\Common */

/** @var \WeltPixel\GA4\Helper\TiktokPixelTracking $tiktokPixelHelper */
$tiktokPixelHelper = $this->helper('WeltPixel\GA4\Helper\TiktokPixelTracking');
$cspNonceProvider = $tiktokPixelHelper->getCspNonceProvider();
$eventId = $tiktokPixelHelper->getEventUID();
?>
<?php if ($tiktokPixelHelper->isTiktokPixelTrackingEnabled() && $tiktokPixelHelper->shouldTiktokPixelEventBeTracked(\WeltPixel\GA4\Model\Config\Source\TiktokPixel\TrackingEvents::EVENT_INITIATE_CHECKOUT)) :
?>
<script <?php if ($cspNonceProvider) /* @noEscape */ echo ' nonce="' .  $cspNonceProvider->generateNonce() . '" ' ?>>
        if (window.ga4AllowServices) {
            ttq.track('InitiateCheckout', {
                "contents": <?= /* @noEscape */ $block->getCheckoutContents() ?>,
                "value": <?= /* @noEscape */ $block->getCheckoutValue() ?>,
                "currency": "<?= /* @noEscape */ $tiktokPixelHelper->getCurrencyCode() ?>"
            },{
                "event_id": '<?= /* @noEscape */ $eventId ?>'
            });
        }
</script>
<?php endif; ?>


<?php if ($tiktokPixelHelper->isServerSideTrackingEnabled() && $tiktokPixelHelper->shouldTikTokServerSideEventBeTracked(\WeltPixel\GA4\Model\Config\Source\TiktokPixel\TrackingEvents::EVENT_INITIATE_CHECKOUT)) : ?>
    <script  <?php if ($cspNonceProvider) /* @noEscape */ echo ' nonce="' .  $cspNonceProvider->generateNonce() . '" ' ?>>
        requirejs(['jquery'],
            function  ($) {
                $(document).ready(function() {
                    var requestUrl = '<?php echo $block->escapeUrl($tiktokPixelHelper->getTikTokSSTrackUrl()); ?>';
                    $.post({
                        url: requestUrl,
                        global: false,
                        data: {
                            'eventId': '<?= /* @noEscape */ $eventId ?>',
                            'eventName': '<?= /* @noEscape */ \WeltPixel\GA4\Model\Config\Source\TiktokPixel\TrackingEvents::EVENT_INITIATE_CHECKOUT  ?>',
                            'pageUrl': '<?= $block->escapeUrl($tiktokPixelHelper->getStoreCurrenUrl()) ?>',
                            'quoteId': '<?=  /* @noEscape */ $block->getQuoteId() ?>'
                        }
                    });
                });
            });
    </script>
<?php endif; ?>
