<?php
/**
 * @author i95Dev Team
 * @copyright Copyright (c) 2019 i95Dev(https://www.i95dev.com)
 * @package I95DevConnect_DiscountGroups
 */


// phpcs:ignoreFile

/** @var $block Renderer */

use Magento\Checkout\Block\Item\Price\Renderer;

$_item = $block->getItem();
?>
<span class="price-excluding-tax" data-label="<?php echo $block->escapeHtml(__('Excl. Tax'));?>">
    <span class="cart-price">
        <?php /* @escapeNotVerified */ echo $this->helper('Magento\Checkout\Helper\Data')->formatPrice($block->getRowTotal($_item)) ?>
    </span>
</span>
