<?php
/**
 * @package Magedelight_Megamenu for Magento 2
 * @author MageDelight Team
 * @copyright Copyright (c) MageDelight (https://www.magedelight.com) owned by Krish TechnoLabs. All Rights reserved.
 */
?>
<input type="hidden" class="hiddenItems" name="menu_data[{{id}}][item_id]" value="{{id}}">
<input type="hidden" class="hiddenItems" name="menu_data[{{id}}][sort_order]" value="{{count}}">
<input type="hidden" class="hiddenItems" name="menu_data[{{id}}][item_parent_id]" value="{{parentId}}">
<input type="hidden" class="hiddenItems" name="menu_data[{{id}}][item_name]" value="{{name}}">
<input type="hidden" class="hiddenItems" name="menu_data[{{id}}][item_type]" value="{{type}}">
<input type="hidden" class="hiddenItems" name="menu_data[{{id}}][object_id]" value="{{objectid}}">
<input type="hidden" class="hiddenItems" name="menu_data[{{id}}][item_link]" value="{{link}}">
<input type="hidden" class="hiddenItems" name="menu_data[{{id}}][item_font_icon]" value="{{fontIcon}}">
<input type="hidden" class="hiddenItems" name="menu_data[{{id}}][item_class]" value="{{itemClass}}">
<input type="hidden" class="hiddenItems" name="menu_data[{{id}}][animation_option]" value="{{animationField}}">
<input type="hidden" class="hiddenItems" name="menu_data[{{id}}][item_all_cat]" value="{{cat}}">
<input type="hidden" class="hiddenItems" name="menu_data[{{id}}][product_display]" value="{{productDisplay}}">
<input type="hidden" class="hiddenItems" name="menu_data[{{id}}][open_in_new_tab]" value="{{openInNewTab}}">
<input type="hidden" class="hiddenItems" name="menu_data[{{id}}][item_vertical_menu]" value="{{verticalMenu}}">
<input type="hidden" class="hiddenItems" name="menu_data[{{id}}][vertical_menu_bgcolor]" value="{{verticalMenuBgColor}}">
<input type="hidden" class="hiddenItems" name="menu_data[{{id}}][vertical_cat_sortby]" value="{{catSortBy}}">
<input type="hidden" class="hiddenItems" name="menu_data[{{id}}][vertical_cat_sortorder]" value="{{catSortOrder}}">
