<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
//phpcs:disable Generic.Files.LineLength
?>
<?php /** @var \Magento\VisualMerchandiser\Block\Adminhtml\Category\Merchandiser\Tile $block */ ?>
<?php
/** @var \Magento\Catalog\Helper\Image $imageBlock */
$imageHelper =  $block->getImageHelper();
?>
<div data-role="img_product_merchandiser">
    <div class="admin__data-grid-header admin__data-grid-toolbar">
        <div class="admin__data-grid-header-row"> </div>
        <div class="admin__data-grid-header-row">
            <div class="admin__control-support-text">
                <?php $countRecords = $block->getCollection()->getSize(); ?>
                <span id="<?= /* @noEscape */ $block->getHtmlId() ?>-total-count" <?= /* @noEscape */ $block->getUiId('total-count') ?>>
                    <?= $escaper->escapeHtml($countRecords) ?>
                </span>
                <?= $escaper->escapeHtml(__('records found')) ?>
            </div>
            <?php if ($block->getPagerVisibility()): ?>
                <div class="admin__data-grid-pager-wrap">
                    <select name="<?= $escaper->escapeHtmlAttr($block->getVarNameLimit()) ?>"
                            id="<?= /* @noEscape */ $block->getHtmlId() ?>_page-limit"
                            data-role="page_limiter"
                            class="admin__control-select">
                        <?php foreach ([20, 30, 50, 100, 200] as $perPageSize): ?>
                            <option value="<?= /* @noEscape */ $perPageSize ?>"<?= ($block->getCollection()->getPageSize() == $perPageSize) ? ' selected="selected"' : ''?>>
                                <?= /* @noEscape */ $perPageSize ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                    <label for="<?= /* @noEscape */ $block->getHtmlId() ?><?= /* @noEscape */ $block->getHtmlId() ?>_page-limit"
                           class="admin__control-support-text"><?= $escaper->escapeHtml(__('per page')) ?></label>

                    <div class="admin__data-grid-pager">
                        <?php $_curPage = $block->getCollection()->getCurPage() ?>
                        <?php $_lastPage = $block->getCollection()->getLastPageNumber() ?>
                        <?php if ($_curPage > 1): ?>
                            <button class="action-previous"
                                    type="button"
                                    data-role="button_previous"
                                    data-value="<?= /* @noEscape */ $_curPage - 1 ?>">
                                <span><?= $escaper->escapeHtml(__('Previous page')) ?></span>
                            </button>
                        <?php else: ?>
                            <button type="button" class="action-previous disabled"><span><?= $escaper->escapeHtml(__('Previous page')) ?></span></button>
                        <?php endif; ?>
                        <input type="text"
                               id="<?= /* @noEscape */ $block->getHtmlId() ?>_page-current"
                               name="<?= $escaper->escapeHtmlAttr($block->getVarNamePage()) ?>"
                               value="<?= $escaper->escapeHtmlAttr($_curPage) ?>"
                               class="admin__control-text"
                               data-role="input_page"
                               <?= /* @noEscape */ $block->getUiId('current-page') ?> />
                        <label class="admin__control-support-text" for="<?= /* @noEscape */ $block->getHtmlId() ?>_page-current">
                            <?= $escaper->escapeHtml(__('of %1', '<span>' . $block->getCollection()->getLastPageNumber() . '</span>'), ['span']) ?>
                        </label>
                        <?php if ($_curPage < $_lastPage): ?>
                            <button type="button"
                                    title="<?= $escaper->escapeHtmlAttr(__('Next page')) ?>"
                                    class="action-next"
                                    data-role="button_next"
                                    data-value="<?= /* @noEscape */ $_curPage  + 1 ?>">
                                <span><?= $escaper->escapeHtml(__('Next page')) ?></span>
                            </button>
                        <?php else: ?>
                            <button type="button" class="action-next disabled"><span><?= $escaper->escapeHtml(__('Next page')) ?></span></button>
                        <?php endif; ?>
                    </div>
                </div>
            <?php endif ?>
        </div>
    </div>

    <?php if ($block->getCollection()): ?>
        <div class="admin__data-grid-wrap admin__data-grid-wrap-static">
            <div class="hor-scroll">
                <ul id="img_product_merchandiser_list" class="catalog-category-merchandiser-list">
                    <?php foreach ($block->getCollection() as $_index => $_product): ?>
                        <?php /** @var \Magento\Catalog\Model\Product $_item */ ?>
                        <li class="product_tile">
                            <div class="controlbar-top">
                                <a href="#" class="icon-gripper"><span><?= $escaper->escapeHtml(__('Draggable')) ?></span></a>
                                <a href="#" class="remove-product icon-close-mage"><span><?= $escaper->escapeHtml(__('Close')) ?></span></a>
                            </div>
                            <div class="image-holder">
                                <img src="<?= $escaper->escapeUrl($block->getImageUrl($_product)) ?>" alt="<?= $escaper->escapeHtmlAttr(__('Product image')) ?>" />
                            </div>
                            <div class="info-block">
                                <?php foreach ($block->getAttributesToDisplay($_product) as $attribute): ?>
                                    <?= /* @noEscape */ $attribute->render() ?>
                                <?php endforeach; ?>
                            </div>
                            <div class="controlbar-bottom">
                                <div class="position">
                                    <label for="id_position_<?= $escaper->escapeHtmlAttr($_index) ?>"><?= $escaper->escapeHtml(__('Position')) ?></label>
                                    <div>
                                        <a href="#" class="move-top icon-backward"><span><?= $escaper->escapeHtml(__('Top')) ?></span></a>
                                        <input type="text" name="position" id="id_position_<?= $escaper->escapeHtmlAttr($_index) ?>" value="<?= $escaper->escapeHtmlAttr($_product->getPosition()) ?>" />
                                        <a href="#" class="move-bottom icon-forward"><span><?= $escaper->escapeHtml(__('Bottom')) ?></span></a>
                                    </div>
                                </div>
                                <input type="hidden" name="entity_id" value="<?= $escaper->escapeHtmlAttr($_product->getId()) ?>" />
                            </div>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    <?php endif; ?>
</div>

<script type="text/x-magento-init">
{
    "[data-role=img_product_merchandiser]": {
        "Silk_ProductImage/js/pager": {
            "gridUrl": "<?= $escaper->escapeJs($block->getGridUrl()) ?>",
            "varNamePage": "<?= $escaper->escapeJs($block->getVarNamePage()) ?>"
        }
    }
}
</script>
