<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div class="admin__data-grid-outer-wrap" data-bind="scope: 'img_product_listing.img_product_listing'">
    <div data-role="spinner" data-component="img_product_listing.img_product_listing.img_product_columns" class="admin__data-grid-loading-mask">
        <div class="spinner">
            <span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span>
        </div>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
