<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var \Silk\ProductImage\Block\Adminhtml\Product\AddProduct\Tabs\SkuTab $block */ ?>
<div data-mage-init='{"Silk_ProductImage/js/mass_sku": {"massAssignButton": ".massassign-button", "massAssignUrl": "<?= $escaper->escapeUrl($block->getMassAssignUrl()) ?>"}}'>
    <form id="add_product_sku_form">
        <div class="massassign-messages" data-role="messages"></div>
        <div class="admin__field">
            <label class="admin__field-label" for="add_product_sku">
                <span><?= $escaper->escapeHtml(__('Enter SKUs below, one per line')) ?></span>
            </label>
            <div class="admin__field-control">
                <textarea name="add_product_sku"
                          id="add_product_sku"
                          class="admin__control-textarea massassign-textarea"
                          cols="64"
                          rows="16"></textarea>
            </div>
        </div>
        <div class="massassign-buttons">
            <button type="button" id="add_product_sku_add_button" class="action-primary massassign-button" role="assign">
                <?= $escaper->escapeHtml(__('Assign')) ?>
            </button>
            <button type="button" id="add_product_sku_remove_button" class="action-secondary massassign-button" role="remove">
                <?= $escaper->escapeHtml(__('Remove')) ?>
            </button>
        </div>
    </form>
</div>
