<?php
/**
 * @package Magedelight_Megamenu for Magento 2
 * @author MageDelight Team
 * @copyright Copyright (c) MageDelight (https://www.magedelight.com) owned by Krish TechnoLabs. All Rights reserved.
 */

$menu_id = $block->getMenuId();
$menu = $block->getMenu();
$customerGroups = $block->getCustomerGroups();
$selecteAll = false;
$selectedCustomerGroups = [];
if ($menu->getCustomerGroups() == null) {
    $selecteAll = true;
} else {
    $selectedCustomerGroups = explode(',', $menu->getCustomerGroups());
}
?>
<select class="admin__control-multiselect required-entry" multiple=""
    name="customer_groups[]" id="customer_groups" size="6">
    <?php
    foreach ($customerGroups as $groupId => $code) {
        $selected = '';
        if (in_array($groupId, $selectedCustomerGroups) || $selecteAll) {
            $selected = "selected = 'selected'";
        }
        ?>
        <option <?= /* @noEscape */ $selected; ?> value="<?= /* @noEscape */ $groupId; ?>">
            <?= /* @noEscape */ $code; ?></option>
        <?php
    }
    ?>
</select>
