<?php
/**
 * @package Magedelight_Megamenu for Magento 2
 * @author MageDelight Team
 * @copyright Copyright (c) MageDelight (https://www.magedelight.com) owned by Krish TechnoLabs. All Rights reserved.
 */

$menu_id = $block->getMenuId();
$menu = $block->getMenu();
$disabledoption = '';
/*if ($menu_id) {
    $disabledoption = 'disabled';
}*/
?>
<select <?= /* @noEscape */ $disabledoption; ?>
    class="admin__control-multiselect required-entry"
    multiple="" name="store_id[]" id="store_id" size="6">
    <?php
    $storeId = $menu->getStoreId();

    $defaultSelected = 'selected';
    if (!empty($storeId)) {
        if (in_array('0', $storeId)) {
            $defaultSelected = 'selected';
        } else {
            $defaultSelected = '';
        }
    }
    ?>
    <option <?= /* @noEscape */ $defaultSelected; ?> data-title="All Store Views" value="0">
        <?= /* @noEscape */ __('All Store Views'); ?>
    </option>
    <?php
    foreach ($block->getContext()->getStoreManager()->getWebsites() as $website) {
        foreach ($website->getGroups() as $group) {
            $stores = $group->getStores();
            foreach ($stores as $store) {
                $storeselect = '';
                if (!empty($storeId)) {
                    if (in_array($store->getStoreId(), $storeId)) {
                        $storeselect = 'selected';
                    }
                }
                ?>
                <optgroup label="<?= /* @noEscape */ $website->getName(); ?>"></optgroup>
                <optgroup label="&nbsp;&nbsp;&nbsp;&nbsp;<?= /* @noEscape */ $group->getName(); ?>">
                    <option <?= /* @noEscape */ $storeselect; ?> value="<?= /* @noEscape */ $store->getStoreId(); ?>">
                        <?= /* @noEscape */ $store->getName(); ?></option>
                </optgroup>
                <?php
            }
        }
    }
    ?>
</select>
