<?php
/**
 * @package Magedelight_Megamenu for Magento 2
 * @author MageDelight Team
 * @copyright Copyright (c) MageDelight (https://www.magedelight.com) owned by Krish TechnoLabs. All Rights reserved.
 */

$selectedOptions = $block->getSelectedOptions();
$name = $block->getName();
$position = $block->getPosition();
$getRandLabel = $block->getRandLabel();
?>
<select class="enable_blocks admin__control-select"
        name="<?= /* @noEscape */ $name; ?>"
        data-position="<?= /* @noEscape */ $position; ?>">
    <option <?php if ($selectedOptions === "0") {
        echo "selected";
            } ?> value="0"><?= /* @noEscape */  __('No'); ?></option>
    <option <?php if ($selectedOptions === "1") {
        echo "selected";
            } ?> value="1"><?= /* @noEscape */ __('Yes'); ?></option>
</select>
